add_newline = true
[python]
disabled = true
[character]
symbol = "â¯"
error_symbol = "âœ—" vicmd_symbol = "â®" use_symbol_for_status = true 
[time]
disabled = false
format = "ğŸ•™%T"

[line_break]
disabled = true
